[theme_new]
primaryColor="#F6F6F3"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#0057A3"
textColor="#262730"
font="sans serif"

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"